# Transpose of Numpy Array :- np.transpose()



In [2]:
import numpy as np

a =  np.array([[1,2,3],[4,5,6]])

print("Array a  : " , '\n' , a )
print("Shape of A : " , a.shape)

print()

b = a.transpose()

print("Array b  : " , '\n' , b )
print("Shape of B : " , b.shape)

Array a  :  
 [[1 2 3]
 [4 5 6]]
Shape of A :  (2, 3)

Array b  :  
 [[1 4]
 [2 5]
 [3 6]]
Shape of B :  (3, 2)


# Squeezing a Numpy Array :- np.squeeze()



In [7]:
x = np.array([[[1,2,3],[4,5,6]]])

print("Array X is : " , '\n' , x)
print("Shape of x " ,x.shape)

print()

y = np.squeeze(x,0)

print("Array y is : " , '\n' , y)
print("Shape of y " ,y.shape)

Array X is :  
 [[[1 2 3]
  [4 5 6]]]
Shape of x  (1, 2, 3)

Array y is :  
 [[1 2 3]
 [4 5 6]]
Shape of y  (2, 3)


# Flip :-np.flip() method to reverse values in Numpy Array

In [12]:
a = np.array([[1,2,3],[4,5,6]])

print("Array a  : " , '\n' , a )
print("Shape of A : " , a.shape)

print()

print("To interchange Rows  : " , '\n',np.flip(a,axis=0))

print()

print("To interchange Columns : " , '\n' , np.flip(a,axis=1))

Array a  :  
 [[1 2 3]
 [4 5 6]]
Shape of A :  (2, 3)

To interchange Rows  :  
 [[4 5 6]
 [1 2 3]]

To interchange Columns :  
 [[3 2 1]
 [6 5 4]]


# Indexing & Slicing of Numpy Array

[start : end : step-size]

In [25]:
a = np.array([10,20,30,40,50,60,70,80,90])
#              0  1  2  3  4  5  6  7  8
#             -9  -8 -7 -6 -5 -4 -3 -2 -1

print(a[5])
print(a[-3])

print(a[:4])# if we don't specify start vaule it will always take zero as start
print(a[2:])# if we don't specify end vaule it will iterate till last element



print(a[0:7:2])

print(a[-5:-1])

print(a[-7:-2])

60
70
[10 20 30 40]
[30 40 50 60 70 80 90]
[10 30 50 70]
[50 60 70 80]
[30 40 50 60 70]


In [34]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(x)

print()

print(x[1,1])

print(x[2,0])

print(x[0,1])

print()

print(x[0:2])#row : -- > 0/1

print(x[0:2,0:3])

print(x[1:3,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

5
7
2

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]
