# NumPy
NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

# What is NumPy?
It is a library consisting of multidimensional array objects and a collection of routines for processing those arrays.

NumPy has put python lists out of the job as NumPy arrays are more efficient, convenient and makes it faster to read or write an item.

# Python Lists vs NumPy Arrays – What’s the Difference?
1.Python lists act as an array that can store elements of various types.A list is the Python equivalent of an array,but is resizeable and can contain elements of different types.

2.NumPy arrays that contain only homogeneous elements, i.e. elements having the same data type.

3.With NumPy arrays, you can perform element-wise operations, something which is not possible using Python lists!

4.This is the reason why NumPy arrays are preferred over Python lists when performing mathematical operations on a large amount of data.

# Why use NumPy?
Using NumPy, mathematical and logical operations on arrays can be performed. NumPy also provides high performance.Some of the key features that contribute in the popularity of NumPyare:

1.It is a powerful N-dimensional array object

2.It is a sophisticated broadcasting functions

3.It is a tool for integrating C/C++ and Fortran code

4.It is useful linear algebra, Fourier transform, and random number capabilities

# Import Convention
Since NumPy is a Python Library, it has to be imported first before you start using NumPy. To import NumPy, type in the following command:

In [3]:
import numpy as np

# Creating Numpy Arrays

1.np.array() 1D/2D

2.np.zeros/ones/identity()

3.np.arange()

4.np.linspace()

5.np.copy()

6.np.random() :--. rand/randint

7.np.full()

In [4]:
#1.np.array() 1D/2D

L1 = [1,2,3,4]

R1 = np.array([1,2,3,4])

print("L1  using List : " , L1)
print("R1  using Numpy Array : " , R1) #1-D array

R2 = np.array([[1,2,3],[4,5,6]]) #2-D Array

print("2D Array " , '\n' , R2)

L1  using List :  [1, 2, 3, 4]
R1  using Numpy Array :  [1 2 3 4]
2D Array  
 [[1 2 3]
 [4 5 6]]


In [8]:
#2.np.zeros/ones/identity()

r1 = np.zeros((2,3))

print("Using Zeros : " , '\n' , r1)

r2 = np.ones((3,2))

print("Using Ones : " , '\n' , r2)

r3 = np.identity(4)

print("Using Identity: " , '\n' , r3)


Using Zeros :  
 [[0. 0. 0.]
 [0. 0. 0.]]
Using Ones :  
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Using Identity:  
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#3.np.arange()

L1 = list(range(1,11))

print("Using Python Range Function : " , L1)

R1 = np.arange(1,11)

print("Using Numpy Range Function : " , R1)

R2 = np.arange(10,50,2)

print("Using Numpy Range Function : " , R2)




Using Python Range Function :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Using Numpy Range Function :  [ 1  2  3  4  5  6  7  8  9 10]
Using Numpy Range Function :  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [18]:
#3.np.linspace()

r1 = np.linspace(0,1,5)

print(r1)

r2 = np.linspace(10,50,2)

print(r2)

#np.copy()

r3 = r2.copy()

print(r3)

[0.   0.25 0.5  0.75 1.  ]
[10. 50.]
[10. 50.]


In [10]:
#6.np.random() :--. rand/randint

r1 =  np.random.rand(3,6) # 0-1 

print(r1)

r2 = np.round( np.random.rand(3,6) , decimals =2)

print(r2)

r2 = np.random.randint(10,50 ,5)

print(r2)

[[0.14041922 0.56032426 0.83804847 0.67710119 0.0955183  0.98167524]
 [0.12229236 0.72987581 0.34816863 0.17351351 0.97080335 0.73223539]
 [0.30077669 0.20762228 0.03654397 0.29254203 0.6718925  0.65984318]]
[[0.46 0.57 0.58 0.   0.99 0.86]
 [0.29 0.26 0.24 0.43 0.03 0.19]
 [0.59 0.93 0.56 0.93 0.1  0.46]]
[14 32 17 35 22]


In [49]:
#7.np.full()

r1 = np.full((2,3),11)

print(r1)

[[11 11 11]
 [11 11 11]]
