In [1]:
import numpy as np

L1 = [1,2,3]
L2 = [4,5,6]

print(L1+L2)

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print('Add of Two Numpy Array : ' , a1+a2)

[1, 2, 3, 4, 5, 6]
Add of Two Numpy Array :  [5 7 9]



# Broadcasting in NumPy arrays

Broadcasting essentially stretches the smaller ndarray so that it matches the shape of the larger ndarray

In [12]:
a = np.arange(1,5)

print(a)

b = np.array([[2],[3],[4]])

print(b)

print("Add of a and b is : " , '\n' , a+b)

[1 2 3 4]
[[2]
 [3]
 [4]]
Add of a and b is :  
 [[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [15]:
b = np.ones([2,3])

print(b)

print()

print(b*5)

[[1. 1. 1.]
 [1. 1. 1.]]

[[5. 5. 5.]
 [5. 5. 5.]]


In [17]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(a+b)

[2 4 6 8]


# Maths with NumPy arrays

In [24]:
a = np.array([[1,2,3],[4,5,6]])

print("Add of a + 4 is : " , '\n' , a+4)
print("Sub of a - 4 is : " , '\n' , a-4)
print("Mult of a * 4 is : " , '\n' , a*4)
print("Div of a / 4 is : " , '\n' , a/4)

print("Power of 2 : " , '\n' , a**15)

Add of a + 4 is :  
 [[ 5  6  7]
 [ 8  9 10]]
Sub of a - 4 is :  
 [[-3 -2 -1]
 [ 0  1  2]]
Mult of a * 4 is :  
 [[ 4  8 12]
 [16 20 24]]
Div of a / 4 is :  
 [[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]
Power of 2 :  
 [[         1      32768   14348907]
 [1073741824  452807053 2033549312]]


In [89]:
x = np.random.randint(1,50 , size = (3,4))

print(x)

print()
print("Value more than 25 : " ,x[x>25])

[[15  4 33 37]
 [13 37 43  4]
 [40 38 32 47]]

Value more than 25 :  [33 37 37 43 40 38 32 47]


# Mean, Median and Standard deviation

In [93]:
x = np.arange(10,50,5)
print(x) #27.5

print("Mean value of Data Set x is : " , np.mean(x))
print("Median value of Data Set x is : " , np.median(x))
print("Standard deviation value of Data Set x is : " , np.std(x))

[10 15 20 25 30 35 40 45]
Mean value of Data Set x is :  27.5
Median value of Data Set x is :  27.5
Standard deviation value of Data Set x is :  11.4564392373896


# Append

In [5]:
a = np.array([[1,2],[3,4]])

print(a)

b= np.append(a,[[5,6]] , axis =0)

print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


# Max and Min

In [37]:
x = np.random.randint(10,50 , size=(2,3))

print(x)

print("max value in X : " , np.max(x))
print("min value in X : " , np.min(x))
print("Varinace in x " , np.var(x))
print("Suare root of X variables : " , '\n', np.sqrt(x))
print("Log of 10 of X variables : " , '\n', np.log10(x))

[[29 45 33]
 [34 33 43]]
max value in X :  45
min value in X :  29
Varinace in x  33.47222222222222
Suare root of X variables :  
 [[5.38516481 6.70820393 5.74456265]
 [5.83095189 5.74456265 6.55743852]]
Log of 10 of X variables :  
 [[1.462398   1.65321251 1.51851394]
 [1.53147892 1.51851394 1.63346846]]


# Sort

In [38]:
a = np.array([25,13,10,45,18,20,14,16,20,13])

print("Sorted order of a : " , np.sort(a))

Sorted order of a :  [10 13 13 14 16 18 20 20 25 45]
