# Numpy Array Dimension / shape / size

In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[4,5,6]])

print("Arra a " , '\n' , a)

print("Shape of Array a is : " , a.shape)

print("Dim of Array a is : " , a.ndim)

print("No of Values in Array a : " , a.size)


print()


b = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print("Arra b " , '\n' , b)

print("Shape of Array b is : " , b.shape)#(3,3)

print("Dim of Array b is : " , b.ndim)#2d

print("No of Values in Array b : " , b.size)#9

Arra a  
 [[1 2 3]
 [4 5 6]]
Shape of Array a is :  (2, 3)
Dim of Array a is :  2
No of Values in Array a :  6

Arra b  
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Shape of Array b is :  (1, 3, 3)
Dim of Array b is :  3
No of Values in Array b :  9


In [3]:
a3 = np.array([[1,2,3],[4,5,6]])

print(a3.ndim)
print(a3.shape)
print(a3.size)

2
(2, 3)
6


In [6]:
a4 = np.array([1,2,3,4,5,6])


b=a4.reshape(2,3)

b

a5 = np.arange(1,11)

c=a5.reshape(5,2)

c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Reshaping of Numpy Array

In [17]:
x = np.arange(1,11)

print(x)
print("Shape of x " ,x.shape)

print()

y = x.reshape(5,2)

print(y)
print("Shape of y " , y.shape)

print()

a = np.array([1,2,3,4,5,6])
print(a)

b= a.reshape(2,3)

print(b)




[ 1  2  3  4  5  6  7  8  9 10]
Shape of x  (10,)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Shape of y  (5, 2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# flatten & ravel

In [22]:
#flatten :---. shallow copy

a = np.array([[1,2,3],[4,5,6]])

print("Orignal Object : " , '\n' , a)

b= a.flatten()

b[0] = 25
print("after using flatten  : " , '\n' , b)

print("after chaging value in b : " , '\n' , a)

Orignal Object :  
 [[1 2 3]
 [4 5 6]]
after using flatten  :  
 [25  2  3  4  5  6]
after chaging value in b :  
 [[1 2 3]
 [4 5 6]]


In [24]:
#ravel :---> deep copy

a = np.array([[1,2,3],[4,5,6]])

print("Orignal Object : " , '\n' , a)

b = a.ravel()

b[0] = 25

print("after using flatten  : " , '\n' , b)

print("after chaging value in b : " , '\n' , a)


Orignal Object :  
 [[1 2 3]
 [4 5 6]]
after using flatten  :  
 [25  2  3  4  5  6]
after chaging value in b :  
 [[25  2  3]
 [ 4  5  6]]
